### ISSUE TITLE
Topics from Reddit?

### ISSUE THREAD

**Issue by solus-impar** [solus-impar/slack-topics#11]
Are there any thoughts or interest in sourcing slack topics from this [subreddit](https://reddit.com/r/cscareerquestions/top/?t=week)? I'm hesitant to have a bot automatically post reddit threads, but it would be interesting to see posts like [this](https://redd.it/6ez8ag) and [this](https://redd.it/6ndohd).

```python
@topic
def top_cscq_post():
    """Top post from reddit.com/r/CSCareerQuestions for the past week."""
    cscq_url = 'https://reddit.com/r/cscareerquestions/top/?t=week'
    cscq_soup = url_to_soup(cscq_url)
    cscq_table = cscq_soup.find('div', class_='sitetable linklisting')
    cscq_post = cscq_table.find('a', href=True)
    post_url = "https://reddit.com{}".format(cscq_post['href'])

    return cscq_post.text, post_url, ''
```

**Comment by reillysiemens** [comment]
Personally I'm hesitant to have a bot automatically post Reddit threads as well. The posts you linked are excellent, but in my experience they're diamonds in the rough and signal to noise ratio could be quite high. Selecting from the top posts for the week would probably help with that, but who knows how much? Maybe scrape the top posts for a few weeks and see if they've been valuable before throwing this one into the mix.
