### ISSUE TITLE
Unicode topic callables and uncamel

### ISSUE THREAD

**Issue by reillysiemens** [solus-impar/slack-topics#9]
I don't think the `uncamel` function can support unicode. If proper unicode support is something that interests you it _should_ be possible to name a class or function like so
```python
@topic
class ΛλΛ:
    def __call__(self):
        return self.__topic__, 'message', '#general'
```
and get
```python
>>> ΛλΛ.__topic__
'Λλ Λ'
```
In order for that to work `uncamel` will have to be able to to translate
```python
>>> uncamel('ΛλΛ')
'λλ_λ'
```
Instead, however, we get
```python
uncamel('ΛλΛ')
'λλλ'
```

**Comment by solus-impar** [comment]
I haven't found a solution for [re](https://docs.python.org/3/library/re.html) yet, but I have found something that works with [regex](https://pypi.python.org/pypi/regex/)

```python
>>> regex.sub(r'([\p{Ll}\d])([\p{Lu}])', r'\1_\2', 'ΛλΛ').lower()
'λλ_λ'
```

**Comment by reillysiemens** [comment]
That seems reasonable to me. Looks like a pretty lightweight dependency.

**Comment by solus-impar** [comment]
I don't know why I didn't try this a year ago.
```python
In [1]: import re

In [2]: re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', 'ΛλΛ').lower()
Out[2]: 'λλλ'

In [3]: re.sub(r'([\w{Ll}\d])([\w{Lu}])', r'\1_\2', 'ΛλΛ').lower()
Out[3]: 'λ_λλ'
```

**Comment by reillysiemens** [comment]
Even better. :grin:
